### ISSUE TITLE
[Bug Report] Some places still use the old data system

### ISSUE THREAD

**Issue by Minion3665** [dragdev-studios/guildmanager#13]
**Describe the bug**
Some places still check for the ID of the bot in the data

**To Reproduce**
Steps to reproduce the behaviour:
1. Load the cog
2. Update your server icon (or trigger on_guild_update in another way)

**Expected behaviour**
The bot shouldn't error

**Traceback**
```
Ignoring exception in on_guild_update
Traceback (most recent call last):
  File "C:\Users\[Redacted]\floobits\share\Minion3665\CAH\venv\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\[Redacted]\floobits\share\Minion3665\CAH\venv\lib\site-packages\guildmanager\cog.py", line 230, in check_guild_banned
    if str(guild.id) in self.data[str(guild.me.id)]["bans"]["servers"].keys():
KeyError: '682696599637458964'
```

**Comment by EEKIM10** [comment]
I thought something was still trying to use that, but couldn't pinpoint. Blame my shitty file text replacement script, since it changed everything else but missed some things, clearly.
