### ISSUE TITLE
[Bug Report] Bot not wanting to start

### ISSUE THREAD

**Issue by WhoTheOOF** [dragdev-studios/guildmanager#4]
screw your formatting eek,

alright so I installed the module on Spirit, added the cog loading code to my boot.py file, restarted my bot after git pulling and now it won't start. thonkery THONKERY THONK *fyi I use python3*

**Comment by WhoTheOOF** [comment]
traceback i finally got from my bot's throat brutally;

`Traceback (most recent call last):
  File "boot.py", line 80, in <module>
    bot.load_extension("guildmanager.cog")
  File "/home/jadon/Bots/spirit-discordlife/venv/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 653, in load_extension
    self._load_from_module_spec(spec, name)
  File "/home/jadon/Bots/spirit-discordlife/venv/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 613, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'guildmanager.cog' raised an error: TypeError: __init__() missing 1 required keyword-only argument: 'name'`

**Comment by WhoTheOOF** [comment]
@dragdev

**Comment by WhoTheOOF** [comment]
Fixed thanks to chromebook.
