### ISSUE TITLE
[Bug Report] Error when trying to use [p]gmd update - module broken?

### ISSUE THREAD

**Issue by WhoTheOOF** [dragdev-studios/guildmanager#6]
I tried to [p]gmd update and it gave me this error `Error reloading updated module: Extension 'guildmanager' has not been loaded.. Traceback has been raised. If this issue persists, please open an issue at https://github.com/dragdev-studios/guildmanager/issues/new.`

I believe the module is broken as I cannot execute the following command, and [p]gmd fucks up too.

```
Traceback (most recent call last):
  File "/home/jadon/Bots/spirit-discordlife/venv/lib/python3.7/site-packages/guildmanager/cog.py", line 194, in gm_update
    self.bot.reload_extension("guildmanager")
  File "/home/jadon/Bots/spirit-discordlife/venv/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 715, in reload_extension
    raise errors.ExtensionNotLoaded(name)
discord.ext.commands.errors.ExtensionNotLoaded: Extension 'guildmanager' has not been loaded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jadon/Bots/spirit-discordlife/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/jadon/Bots/spirit-discordlife/venv/lib/python3.7/site-packages/guildmanager/cog.py", line 198, in gm_update
    raise commands.ExtensionFailed from e
TypeError: __init__() missing 2 required positional arguments: 'name' and 'original'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jadon/Bots/spirit-discordlife/venv/lib/python3.7/site-packages/jishaku/cog.py", line 504, in jsk_debug
    await alt_ctx.command.invoke(alt_ctx)
  File "/home/jadon/Bots/spirit-discordlife/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 1234, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/jadon/Bots/spirit-discordlife/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/jadon/Bots/spirit-discordlife/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() missing 2 required positional arguments: 'name' and 'original'
```

**Comment by WhoTheOOF** [comment]
@dragdev

**Comment by dragdev** [comment]
current work-around is to just manually `bot.reload_extension("guildmanager.cog")` directly or whatever command you use. I am working on a fix

**Comment by EEKIM10** [comment]
Turns out it isn't fixed.
